# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('script', models.TextField(max_length=10240)),
                ('script_changed', models.BooleanField(default=False)),
                ('number_of_nodes', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('cores_per_node', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('local_status', models.IntegerField(choices=[(0, 'NOT_SUBMITTED'), (1, 'SUBMITTED')], default=0)),
                ('remote_status', models.IntegerField(blank=True, choices=[(3, 'RUNNING'), (4, 'QUEUED'), (5, 'COMPLETED'), (6, 'REMOVED'), (7, 'DEFERRED'), (8, 'IDLE'), (9, 'UNKNOWN')], null=True)),
                ('remote_submit_date', models.DateTimeField(blank=True, null=True)),
                ('remote_start_date', models.DateTimeField(blank=True, null=True)),
                ('remote_complete_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_instruments', related_query_name='job_instrument', to='catalog.Instrument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('remote_id', models.IntegerField()),
                ('remote_directory', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to='jobs.Transaction'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_users', related_query_name='job_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
