# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'NOT_SUBMITTED'), (1, 'SUBMITTED'), (3, 'RUNNING'), (4, 'QUEUED'), (5, 'COMPLETED'), (6, 'REMOVED'), (7, 'DEFERRED'), (8, 'IDLE'), (9, 'UNKNOWN')], default=(0, 'NOT_SUBMITTED'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_instruments', related_query_name='job_instrument', to='catalog.Instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_users', related_query_name='job_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
