# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
