# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='script',
            field=models.TextField(),
        ),
    ]
