# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_remote_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
