# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160203_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='script',
            field=models.TextField(max_length=10240),
        ),
    ]
