# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioSANSCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipts', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('label', models.CharField(choices=[('0', ''), ('1', 'Template'), ('2', 'TODO 1'), ('3', 'TODO 2')], default='0', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('empty_transmission_run', models.CharField(max_length=256)),
                ('dark_current_run', models.CharField(max_length=256)),
                ('flood_field_run', models.CharField(max_length=256)),
                ('beam_center_run', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BioSANSScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('data_run', models.CharField(max_length=256)),
                ('background_run', models.CharField(max_length=256)),
                ('transmission_run', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
