# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_usanssanscommon_usanssansscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usanssansscan',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan', related_query_name='scan', to='configuration.USANSSANSCommon'),
        ),
    ]
