# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=56, unique=True)),
                ('visible', models.BooleanField(default=True, help_text='If it will be visible on the main catalog page')),
            ],
            options={
                'ordering': ['short_name'],
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamline', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(blank=True, help_text='Type of instrument: SANS, TOF, etc..', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Instrument description (optional)', max_length=256, verbose_name='description')),
                ('icat_name', models.CharField(blank=True, max_length=32)),
                ('ldap_name', models.CharField(blank=True, max_length=32)),
                ('drive_name', models.CharField(blank=True, max_length=32)),
                ('visible', models.BooleanField(default=True, help_text='If it will be visible on the main catalog page')),
                ('reduction_available', models.BooleanField(default=False, help_text='If there is web reduction available for this instrument')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', related_query_name='facility', to='catalog.Facility')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
    ]
