# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamline', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('icat_name', models.CharField(blank=True, max_length=32)),
                ('facility', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, help_text='Type of instrument: SANS, TOF, etc..', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Instrument description (optional)', max_length=256, verbose_name='description')),
                ('visible', models.BooleanField(default=True, help_text='If it will be visible on the main catalog page')),
                ('reduction_available', models.BooleanField(default=False, help_text='If there is web reduction available for this instrument')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
    ]
