# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
