# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['icat_name'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
    ]
