# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['id'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.CharField(blank=True, help_text='Instrument description (optional)', max_length=256, verbose_name='description'),
        ),
    ]
