# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160104_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='facility',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='icat_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
