# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQSANSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipts', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('dark_current_run', models.CharField(blank=True, max_length=256, null=True)),
                ('beam_center_run', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('absolute_scale_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('sample_thickness', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('sample_aperture_diameter', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('sensitivity_run', models.CharField(blank=True, max_length=256, null=True)),
                ('sensitivity_min', models.DecimalField(decimal_places=2, default=0.4, max_digits=10)),
                ('sensitivity_max', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('direct_beam_run', models.CharField(blank=True, max_length=256, null=True)),
                ('mask_run', models.CharField(blank=True, max_length=256, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument', related_query_name='instrument', to='catalog.Instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EQSANSEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_run', models.CharField(max_length=256)),
                ('sample_transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('background_run', models.CharField(blank=True, max_length=256, null=True)),
                ('background_transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EQSANSReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduction', related_query_name='reduction', to='sans.EQSANSConfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', related_query_name='entry', to='sans.EQSANSReduction'),
        ),
    ]
