# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQSANSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('absolute_scale_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('sample_thickness', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('sample_aperture_diameter', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('mask_file', models.CharField(blank=True, help_text='File path', max_length=256)),
                ('dark_current_file', models.CharField(blank=True, help_text='File path', max_length=256)),
                ('sensitivity_file', models.CharField(blank=True, help_text='File path', max_length=256)),
                ('sensitivity_min', models.DecimalField(decimal_places=2, default=0.4, max_digits=10)),
                ('sensitivity_max', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('direct_beam_file', models.CharField(blank=True, max_length=256, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', related_query_name='instrument', to='catalog.Instrument')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EQSANSEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_scattering', models.CharField(max_length=256)),
                ('sample_transmission', models.CharField(max_length=256)),
                ('background_scattering', models.CharField(max_length=256)),
                ('background_transmission', models.CharField(max_length=256)),
                ('empty_beam', models.CharField(max_length=256)),
                ('save_name', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EQSANSReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('ipts', models.CharField(blank=True, max_length=16, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reductions', related_query_name='reduction', to='sans.EQSANSConfiguration')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='reduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='sans.EQSANSReduction'),
        ),
    ]
