# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqsansconfiguration',
            name='beam_center_run',
        ),
        migrations.RemoveField(
            model_name='eqsansconfiguration',
            name='dark_current_run',
        ),
        migrations.RemoveField(
            model_name='eqsansconfiguration',
            name='mask_run',
        ),
        migrations.RemoveField(
            model_name='eqsansconfiguration',
            name='sensitivity_run',
        ),
        migrations.AddField(
            model_name='eqsansconfiguration',
            name='dark_current_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eqsansconfiguration',
            name='mask_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eqsansconfiguration',
            name='sensitivity_file',
            field=models.CharField(blank=True, help_text='File path', max_length=256, null=True),
        ),
    ]
