# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eqsansentry',
            old_name='sample_run',
            new_name='background_scattering',
        ),
        migrations.RemoveField(
            model_name='eqsansentry',
            name='background_run',
        ),
        migrations.RemoveField(
            model_name='eqsansentry',
            name='background_transmission_run',
        ),
        migrations.RemoveField(
            model_name='eqsansentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eqsansentry',
            name='sample_transmission_run',
        ),
        migrations.RemoveField(
            model_name='eqsansentry',
            name='transmission_run',
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='background_transmission',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 17, 39, 47, 600849, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='empty_beam',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 17, 39, 50, 287967, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='sample_scattering',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 17, 39, 52, 576924, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='sample_transmission',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 17, 39, 55, 920296, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eqsansentry',
            name='save_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
