# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_eqsansconfiguration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqsansconfiguration',
            name='direct_beam_file',
            field=models.CharField(blank=True, default='', help_text='File path', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eqsansconfiguration',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eqsansconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eqsansreduction',
            name='ipts',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eqsansreduction',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
