# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sans', '0002_auto_20160115_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eqsansconfiguration',
            old_name='direct_beam_run',
            new_name='direct_beam_file',
        ),
    ]
